project:
  type: book
  output-dir: _site

book:
  title: "Classical Mechanics Notes"
  author: "dsoldevila"
  site-url: "https://dsoldevila.github.io/classical-mechanics-notes/"
  chapters:
    - index.qmd
    - chapters/01-vectors-and-derivatives.qmd
    - chapters/02-newtonian-mechanics.qmd
    - chapters/03-spaces-trigonometry-and-vectors.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: show
    highlight-style: github